// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-yeOmBeTrzu5565Xwr-ojlV8AWBdT0js',
    appId: '1:932595220305:android:87a871db0cefe6ecbc5d70',
    messagingSenderId: '932595220305',
    projectId: 'quest-c9433',
    databaseURL: 'https://quest-c9433-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quest-c9433.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzLffE9M5Ap-XDG15isApFzLiD-Hjqrv8',
    appId: '1:932595220305:web:a58aa16dbb6ed6c3bc5d70',
    messagingSenderId: '932595220305',
    projectId: 'quest-c9433',
    authDomain: 'quest-c9433.firebaseapp.com',
    databaseURL: 'https://quest-c9433-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quest-c9433.appspot.com',
    measurementId: 'G-C7E2HWCCR5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3MJq9hOYEBfxRmZhXWpdHVJILxgOnx2Q',
    appId: '1:932595220305:ios:c7b660449513a195bc5d70',
    messagingSenderId: '932595220305',
    projectId: 'quest-c9433',
    databaseURL: 'https://quest-c9433-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quest-c9433.appspot.com',
    iosBundleId: 'wsmb.mobile2024.ws02.drivercp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3MJq9hOYEBfxRmZhXWpdHVJILxgOnx2Q',
    appId: '1:932595220305:ios:c7b660449513a195bc5d70',
    messagingSenderId: '932595220305',
    projectId: 'quest-c9433',
    databaseURL: 'https://quest-c9433-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quest-c9433.appspot.com',
    iosBundleId: 'wsmb.mobile2024.ws02.drivercp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzLffE9M5Ap-XDG15isApFzLiD-Hjqrv8',
    appId: '1:932595220305:web:3cc9aeb8edd08478bc5d70',
    messagingSenderId: '932595220305',
    projectId: 'quest-c9433',
    authDomain: 'quest-c9433.firebaseapp.com',
    databaseURL: 'https://quest-c9433-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quest-c9433.appspot.com',
    measurementId: 'G-JYZ9HE876D',
  );

}